import { articlesNotNull } from '$utils/blog-article-not-null';
import { featureCardsTunnel } from '$utils/feature-cards-tunnel';
import { sectionColFeature_2 } from '$utils/feature-cards-tunnel_2';
import { featuresCardsList } from '$utils/features-cards_list';
import { filterFirstButtonClick } from '$utils/filter-first-button-click';
import { footerForm } from '$utils/footer-form';
import { masonryGrid } from '$utils/masonry';
import { nestLinkPervent } from '$utils/nest-links-pervent';
import { pricingPage } from '$utils/pricing-page';
import { swiper_homePageInit } from '$utils/swiper_home-page';
import { swiper_storiesInit } from '$utils/swiper_stories';
import { timeAccordionComponent } from '$utils/time-accordion-component';
import { timeSection_featurePage } from '$utils/time-accordion-component_feature-page';
import { webinarForm } from '$utils/webinar-forms';

window.Webflow ||= [];
window.Webflow.push(() => {
  nestLinkPervent();
  timeAccordionComponent();
  swiper_homePageInit();
  swiper_storiesInit();
  featureCardsTunnel();
  featuresCardsList();
  sectionColFeature_2();
  filterFirstButtonClick();
  articlesNotNull();
  footerForm();
  webinarForm();
  pricingPage();
  timeSection_featurePage();
  masonryGrid();
});
